version: 0.2

phases:
  pre_build:
    commands:
      - echo 'Starting deployment...'
      - aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin 746669226532.dkr.ecr.eu-west-2.amazonaws.com

  build:
    commands:
      - docker build --platform linux/amd64 -t 746669226532.dkr.ecr.eu-west-2.amazonaws.com/elephant:web ./src/UI
      - docker  build --platform linux/amd64 -t 746669226532.dkr.ecr.eu-west-2.amazonaws.com/elephant:web ./src
      - docker push 746669226532.dkr.ecr.eu-west-2.amazonaws.com/elephant:web
  post_build:
    commands:
      - docker image rm 746669226532.dkr.ecr.eu-west-2.amazonaws.com/elephant:latest
